### YamlMime:TopicLanding
title: Insinyur Data di Microsoft Learn
summary: Microsoft Learn membantu Anda menemukan alat dan keterampilan yang Anda butuhkan untuk menjadi Insinyur Data.
metadata:
  ms.topic: landing-page
  ms.prod: non-product-specific
  ms.openlocfilehash: 8547df3a2e4c8618f6b6b1ac1d14c565b386b94d
  ms.sourcegitcommit: ced3f00740c000a8898d4147eb6f6e7e98ec5f2c
  ms.translationtype: HT
  ms.contentlocale: id-ID
  ms.lasthandoff: 08/19/2021
  ms.locfileid: "122438446"
hero:
  title: Microsoft Learn Untuk Insinyur Data
  subTitle: Jadikan data kompleks Anda tersedia dan dapat diakses
  summary: Anda merancang dan mengimplementasikan manajemen, pemantauan, dan keamanan solusi data. Dapatkan keterampilan dan pengetahuan yang diperlukan untuk membangun karir Anda sebagai Insinyur Data yang sukses.
  link:
    url: /learn/browse/?roles=data-engineer
    text: Telusuri semua jalur untuk Insinyur Data
  imageUrl: https://docs.microsoft.com/media/learn/topics/blue-hero-background-03.svg
featuredSection:
- title: Sertifikasi
  subTitle: Dapatkan Sertifikasi
  summary: Tunjukkan keterampilan teknik data Anda dalam streaming data, kegigihan, dan transformasi.
  imageUrl: https://docs.microsoft.com/media/learn/topics/administrator-certifications.svg
  link:
    url: /learn/certifications/roles/data-engineer
    text: Jelajahi Sertifikasi
- title: Pelatihan
  subTitle: Kursus yang dipimpin instruktur
  summary: Pelajari jadwal Anda sendiri dalam pengaturan ruang kelas tradisional, dengan kecepatan Anda sendiri dan di tempat Anda sendiri.
  imageUrl: https://docs.microsoft.com/media/learn/topics/data-scientist.svg
  link:
    url: /learn/certifications/courses/browse/?roles=data-engineer
    text: Menemukan kursus
curatedSection:
- title: Jalur Anda untuk memulai
  items:
  - learn.wwl.realize-integrated-analytical-solutions-with-azure-synapse-analytics
  - learn.wwl.build-oss-analytical-solutions-az-hdinsight
  - learn.wwl.migrate-application-workloads-data-azure
  - learn.data-ai.azure-for-the-data-engineer
  - learn.store-data-in-azure
  - learn.wwl.migrate-sql-workloads-to-azure
trendingSection:
  title: Jalur dan modul pembelajaran populer untuk Insinyur Data
  filters:
    roles:
    - data-engineer
  linkText: Lihat apa yang sedang dipelajari orang lain
